# Generated by Django 4.2.2 on 2023-06-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=150, verbose_name='Объем')),
                ('bulk', models.PositiveIntegerField(verbose_name='Оптом')),
                ('retail', models.PositiveIntegerField(verbose_name='В розницу')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подраздела')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450)),
                ('image', models.ImageField(upload_to='ItemImages/')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('purpose', models.TextField(null=True, verbose_name='Назначение')),
                ('color', models.TextField(null=True, verbose_name='Цвет')),
                ('degree_of_gloss', models.TextField(null=True, verbose_name='Степень глянца')),
                ('warranty', models.TextField(null=True, verbose_name='Гарантия')),
                ('expiration_date', models.TextField(null=True, verbose_name='Срок хранения')),
                ('composition', models.TextField(null=True, verbose_name='Состав')),
                ('method_of_use', models.TextField(null=True, verbose_name='Метод использования')),
                ('expense', models.TextField(null=True, verbose_name='Расход')),
                ('flammable', models.BooleanField(null=True, verbose_name='Огнеопасно')),
                ('traits', models.TextField(null=True, verbose_name='Свойства')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.price')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag')),
            ],
        ),
    ]
