# Generated by Django 4.2.2 on 2023-06-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.TextField(blank=True, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='item',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='item',
            name='degree_of_gloss',
            field=models.TextField(blank=True, null=True, verbose_name='Степень глянца'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expense',
            field=models.TextField(blank=True, null=True, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expiration_date',
            field=models.TextField(blank=True, null=True, verbose_name='Срок хранения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='flammable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Огнеопасно'),
        ),
        migrations.AlterField(
            model_name='item',
            name='method_of_use',
            field=models.TextField(blank=True, null=True, verbose_name='Метод использования'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='traits',
            field=models.TextField(blank=True, null=True, verbose_name='Свойства'),
        ),
        migrations.AlterField(
            model_name='item',
            name='warranty',
            field=models.TextField(blank=True, null=True, verbose_name='Гарантия'),
        ),
    ]
