# Generated by Django 4.2.2 on 2023-06-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_color_alter_item_composition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.ManyToManyField(blank=True, null=True, to='shop.price'),
        ),
    ]
